# Generated by Django 5.0.7 on 2024-07-22 12:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("jti", models.CharField(max_length=255)),
                ("token", models.CharField(max_length=255)),
                (
                    "token_type",
                    models.CharField(
                        choices=[
                            ("access", "access"),
                            ("refresh", "refresh"),
                            ("reset", "reset"),
                            ("verify", "verify"),
                        ],
                        default="access",
                        max_length=15,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_blacklisted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="Email"
                    ),
                ),
                ("name", models.CharField(max_length=70)),
                ("tc", models.BooleanField()),
                ("is_active", models.BooleanField(default=False)),
                ("is_admin", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BlacklistToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jti", models.CharField(editable=False, max_length=255, unique=True)),
                (
                    "token_type",
                    models.CharField(
                        choices=[
                            ("access", "Access"),
                            ("refresh", "Refresh"),
                            ("reset", "Reset"),
                            ("verify", "Verify"),
                        ],
                        editable=False,
                        max_length=7,
                    ),
                ),
                ("blacklisted_on", models.DateTimeField(auto_now_add=True)),
                (
                    "token",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth_api.token",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="token",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="auth_api.user"
            ),
        ),
    ]
