# Generated by Django 5.0.7 on 2024-07-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_admin",
            new_name="is_staff",
        ),
        migrations.RemoveField(
            model_name="user",
            name="tc",
        ),
        migrations.AddField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
