# Generated by Django 5.0.7 on 2024-08-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_api", "0002_rename_is_admin_user_is_superuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auth_provider",
            field=models.CharField(default="email", max_length=255),
        ),
        migrations.AlterField(
            model_name="token",
            name="token_type",
            field=models.CharField(
                choices=[
                    ("access", "access"),
                    ("refresh", "refresh"),
                    ("reset", "reset"),
                    ("verify", "verify"),
                    ("google", "google"),
                ],
                default="access",
                max_length=15,
            ),
        ),
    ]
