# Generated by Django 5.0.7 on 2024-07-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_api", "0002_rename_is_admin_user_is_staff_remove_user_tc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="token",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
