# Generated by Django 5.0.7 on 2024-07-24 09:01

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth_api", "0003_token_is_deleted"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="token",
            managers=[
                ("default", django.db.models.manager.Manager()),
            ],
        ),
    ]
