# Generated by Django 5.0.7 on 2024-07-31 05:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth_api", "0002_rename_is_admin_user_is_superuser"),
        ("auth_api", "0004_alter_token_managers"),
    ]

    operations = []
