# Generated by Django 5.0.7 on 2024-08-09 12:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth_api", "0004_user_date_joined_user_first_name_user_groups_and_more"),
        ("auth_api", "0005_merge_20240731_0542"),
    ]

    operations = []
