# Generated by Django 5.0.7 on 2024-08-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_api", "0006_merge_20240809_1221"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into this admin site.",
                verbose_name="staff status",
            ),
        ),
    ]
