# Generated by Django 5.0.7 on 2024-08-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_api", "0007_remove_user_name_alter_user_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="jti",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
