# Generated by Django 5.0.7 on 2024-08-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_api", "0008_alter_token_jti"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="active"),
        ),
    ]
