# Generated by Django 5.1 on 2024-08-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_api", "0009_alter_user_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="token",
            options={"ordering": ("-created_at",)},
        ),
        migrations.RemoveField(
            model_name="token",
            name="is_blacklisted",
        ),
        migrations.RemoveField(
            model_name="token",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="token",
            name="token",
        ),
        migrations.RemoveField(
            model_name="user",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="token",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="token",
            name="is_blacklist_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="token",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="token",
            name="jti",
            field=models.CharField(
                default="e3f1eab76cd94f7abe04323f94f3ac87", max_length=255, unique=True
            ),
        ),
        migrations.DeleteModel(
            name="BlacklistToken",
        ),
    ]
