# Generated by Django 5.1 on 2024-08-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_api", "0010_alter_token_options_remove_token_is_blacklisted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="token",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="token",
            name="jti",
            field=models.CharField(
                default="865053623dbe4fa99ca934240d68c4f2", max_length=255, unique=True
            ),
        ),
    ]
