# Generated by Django 5.1 on 2024-08-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_api", "0011_token_is_deleted_alter_token_jti"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="jti",
            field=models.CharField(
                default="e4af42f26a094670b03e9d7f8caf1c33", max_length=255, unique=True
            ),
        ),
    ]
