# Generated by Django 5.1 on 2024-08-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_api", "0012_alter_token_jti"),
    ]

    operations = [
        migrations.AddField(
            model_name="token",
            name="token",
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="token",
            name="jti",
            field=models.CharField(
                default="e43c6a4b91324ed6adeaf393ed6470ec", max_length=255, unique=True
            ),
        ),
    ]
