# Generated by Django 5.1 on 2024-08-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_api", "0013_token_token_alter_token_jti"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="jti",
            field=models.CharField(
                default="3625a879c18b45568ff13d994121b249", max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
