# Generated by Django 5.1 on 2024-08-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_api", "0014_alter_token_jti_alter_token_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="token",
            name="token",
        ),
        migrations.AlterField(
            model_name="token",
            name="jti",
            field=models.CharField(
                default="9162d1aeb20f46ef8a20fe20fcb538f2", max_length=255, unique=True
            ),
        ),
    ]
