# Generated by Django 5.1 on 2024-08-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_api", "0015_remove_token_token_alter_token_jti"),
    ]

    operations = [
        migrations.AddField(
            model_name="token",
            name="token",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="token",
            name="jti",
            field=models.CharField(
                default="502bff26f94046dcafa43cd745706260", max_length=255, unique=True
            ),
        ),
    ]
