# Generated by Django 5.1 on 2024-08-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_api", "0016_token_token_alter_token_jti"),
    ]

    operations = [
        migrations.RenameField(
            model_name="token",
            old_name="expires_at",
            new_name="expire_at",
        ),
        migrations.AlterField(
            model_name="token",
            name="jti",
            field=models.CharField(
                default="6ef556514aab4001a81958fba9abc0e4", max_length=255, unique=True
            ),
        ),
    ]
