# Generated by Django 5.1 on 2024-08-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_api", "0017_rename_expires_at_token_expire_at_alter_token_jti"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="jti",
            field=models.CharField(
                default="b722b22882f24f2495cbcfebc329717e", max_length=255, unique=True
            ),
        ),
    ]
