# Generated by Django 5.1 on 2024-08-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_api", "0018_alter_token_jti"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="jti",
            field=models.CharField(
                default="26d3f1bdf26e40df93610f5c36163698", max_length=255
            ),
        ),
    ]
