# Generated by Django 5.1 on 2024-08-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_api", "0019_alter_token_jti"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="jti",
            field=models.CharField(
                default="6cd7d867cd21458db0f3e09cd87a96c4", max_length=255
            ),
        ),
    ]
