# Generated by Django 5.1 on 2024-08-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_api", "0020_alter_token_jti"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="jti",
            field=models.CharField(
                default="d76f90fe30a840de85d393a84bfb0b88", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="token_type",
            field=models.CharField(
                choices=[
                    ("access", "Access"),
                    ("refresh", "Refresh"),
                    ("reset", "Reset"),
                    ("verify", "Verify"),
                    ("google", "Google"),
                ],
                default="access",
                max_length=15,
            ),
        ),
    ]
