# Generated by Django 5.0.7 on 2024-08-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_api", "0020_alter_token_jti"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="jti",
            field=models.CharField(
                default="38e14acacf30494fbdcb2ae07ab1df8a", max_length=255
            ),
        ),
    ]
