# Generated by Django 5.1 on 2024-08-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_api", "0021_alter_token_jti_alter_token_token_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="jti",
            field=models.CharField(
                default="e93d47d0889e421abcd0f9b8a2c52ca9", max_length=255
            ),
        ),
    ]
