# Generated by Django 5.1.1 on 2024-09-17 04:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth_api", "0021_alter_token_jti"),
        ("auth_api", "0022_alter_token_jti"),
    ]

    operations = []
