# Generated by Django 5.0.7 on 2024-09-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_api", "0023_merge_0021_alter_token_jti_0022_alter_token_jti"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="jti",
            field=models.CharField(
                default="bcedb88299414ad488f169e133b74b7b", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="token_type",
            field=models.CharField(
                choices=[
                    ("access", "Access"),
                    ("refresh", "Refresh"),
                    ("reset", "Reset"),
                    ("verify_mail", "Verify Mail"),
                    ("google", "Google"),
                ],
                default="access",
                max_length=15,
            ),
        ),
    ]
