# Generated by Django 5.1.1 on 2024-09-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_api", "0023_merge_0021_alter_token_jti_0022_alter_token_jti"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="token",
            name="jti",
            field=models.CharField(
                default="1752f6f7a30f45e9a7b07e799a857093", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="token_type",
            field=models.CharField(
                choices=[
                    ("access", "Access"),
                    ("refresh", "Refresh"),
                    ("reset", "Reset"),
                    ("verify_mail", "Verify Mail"),
                    ("google", "Google"),
                ],
                default="access",
                max_length=15,
            ),
        ),
    ]
