# Generated by Django 5.0.7 on 2024-09-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_api", "0024_alter_token_jti_alter_token_token_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="jti",
            field=models.CharField(
                default="a8c2a180e76a446884636351c8b90969", max_length=255
            ),
        ),
    ]
