# Generated by Django 5.0.7 on 2024-09-27 10:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth_api", "0024_user_created_at_user_is_deleted_user_updated_at_and_more"),
        ("auth_api", "0025_alter_token_jti"),
    ]

    operations = []
