# Generated by Django 5.0.7 on 2024-09-27 11:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth_api", "0026_merge_20240927_1049"),
        ("auth_api", "0026_merge_20240927_1104"),
    ]

    operations = []
