# Generated by Django 5.0.7 on 2024-10-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_api", "0027_merge_20240927_1135"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="jti",
            field=models.CharField(
                default="82fc0063e07f4c3397bfe23576c119c6", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="token_type",
            field=models.CharField(
                choices=[
                    ("access", "Access"),
                    ("refresh", "Refresh"),
                    ("reset", "Reset"),
                    ("verify_mail", "Verify Mail"),
                    ("google", "Google"),
                    ("otp", "Otp"),
                ],
                default="access",
                max_length=15,
            ),
        ),
    ]
