# Generated by Django 5.0.7 on 2024-10-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_api", "0027_merge_20240927_1135"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="token",
            name="jti",
            field=models.CharField(
                default="a4f4468dea0b407fbcb93be1976f490f", max_length=255
            ),
        ),
    ]
