# Generated by Django 5.0.7 on 2024-10-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_api", "0028_alter_token_jti_alter_token_token_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="jti",
            field=models.CharField(max_length=255),
        ),
    ]
