# Generated by Django 5.0.7 on 2024-10-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_api", "0028_alter_token_jti_alter_token_token_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_default_password",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="token",
            name="jti",
            field=models.CharField(
                default="9a7a9de0bc88447a830716736c3c1b97", max_length=255
            ),
        ),
    ]
