# Generated by Django 5.0.7 on 2024-10-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_api", "0028_user_is_email_verified_alter_token_jti"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="jti",
            field=models.CharField(
                default="68f7d561b74747d2aec2f6e4cdc37500", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
    ]
