# Generated by Django 5.0.7 on 2024-10-03 09:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth_api", "0028_alter_token_jti_alter_token_token_type"),
        ("auth_api", "0029_alter_token_jti_alter_user_is_active"),
    ]

    operations = []
