# Generated by Django 5.0.7 on 2024-10-08 06:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_api", "0029_user_is_default_password_alter_token_jti"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="jti",
            field=models.CharField(
                default="628163f1ea4b4b5883a1aca1d6993efe", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
