# Generated by Django 5.0.7 on 2024-10-07 07:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth_api", "0029_user_is_default_password_alter_token_jti"),
        ("auth_api", "0030_merge_20241003_0954"),
    ]

    operations = []
