# Generated by Django 5.0.7 on 2024-10-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_api", "0030_alter_token_jti_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="jti",
            field=models.CharField(
                default="ce74b06c9fd84411b7842c1e8db0c504", max_length=255
            ),
        ),
    ]
