# Generated by Django 5.0.7 on 2024-10-07 07:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth_api", "0029_alter_token_jti"),
        ("auth_api", "0031_merge_20241007_0703"),
    ]

    operations = []
