# Generated by Django 5.0.7 on 2024-10-08 06:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_api", "0031_alter_token_jti"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="jti",
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
    ]
