# Generated by Django 5.2.1 on 2025-05-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_api", "0032_merge_0029_alter_token_jti_0031_merge_20241007_0703"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="totp_secret",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
