# Generated by Django 5.2.1 on 2025-05-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_api", "0032_merge_0029_alter_token_jti_0031_merge_20241007_0703"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cognito_sub",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="token",
            name="jti",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="token",
            name="token_type",
            field=models.CharField(
                choices=[
                    ("access", "Access"),
                    ("refresh", "Refresh"),
                    ("reset", "Reset"),
                    ("verify_mail", "Verify Mail"),
                    ("google", "Google"),
                    ("otp", "Otp"),
                    ("id_token", "Id Token"),
                ],
                default="access",
                max_length=15,
            ),
        ),
    ]
