# Generated by Django 5.0.7 on 2024-10-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_api", "0032_alter_token_jti"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="jti",
            field=models.CharField(
                default="bae766f7f1814c719433dd0b53038f90", max_length=255
            ),
        ),
    ]
