# Generated by Django 5.0.7 on 2024-10-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("auth_api", "0032_merge_0029_alter_token_jti_0031_merge_20241007_0703"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="auth_api_user_set", to="auth.group"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="auth_api_user_permissions_set",
                to="auth.permission",
            ),
        ),
    ]
