# Generated by Django 5.2.1 on 2025-06-06 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("auth_api", "0033_user_cognito_sub_alter_token_jti_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "redirect_url",
                    models.URLField(
                        default="/", help_text="URL to redirect users of this group"
                    ),
                ),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="auth.group",
                    ),
                ),
            ],
        ),
    ]
