# Generated by Django 5.0.7 on 2024-10-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_api", "0033_alter_token_jti"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="jti",
            field=models.CharField(
                default="93c66a52dacd45ea8e9a2441bf989e99", max_length=255
            ),
        ),
    ]
