# Generated by Django 4.1.3 on 2023-12-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PaymentHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stripe_subscription_id", models.CharField(max_length=255, null=True)),
                ("price_id", models.CharField(max_length=255)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Active"), (2, "Canceled"), (3, "Paused")],
                        default=1,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("current_period_start", models.DateTimeField()),
                ("current_period_end", models.DateTimeField(null=True)),
                ("ip_limit", models.IntegerField(default=1)),
                (
                    "price_type",
                    models.IntegerField(
                        choices=[
                            (1, "Recurring Monthly"),
                            (2, "Recurring Annualy"),
                            (3, "One Time"),
                        ],
                        default=1,
                    ),
                ),
            ],
        ),
    ]
