# Generated by Django 4.1.3 on 2023-10-26 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paymenthostory",
            old_name="ip_to_scan",
            new_name="ip_limit",
        ),
    ]
