# Generated by Django 4.1.3 on 2023-10-26 08:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payments", "0002_rename_ip_to_scan_paymenthostory_ip_limit"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PaymentHostory",
            new_name="PaymentHistory",
        ),
    ]
