# Generated by Django 4.1.3 on 2023-11-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_rename_paymenthostory_paymenthistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenthistory",
            name="price_type",
            field=models.IntegerField(
                choices=[(1, "Recurring"), (2, "One Time")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="paymenthistory",
            name="current_period_end",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="paymenthistory",
            name="stripe_subscription_id",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
