# Generated by Django 4.1.3 on 2023-11-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_paymenthistory_price_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymenthistory",
            name="price_type",
            field=models.IntegerField(
                choices=[
                    (1, "Recurring Monthly"),
                    (2, "Recurring Annualy"),
                    (3, "One Time"),
                ],
                default=1,
            ),
        ),
    ]
