# Generated by Django 5.1 on 2024-08-23 10:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("inventory", models.IntegerField()),
                ("available", models.BooleanField(default=True)),
                ("published_date", models.DateField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("rating", models.FloatField()),
                ("image", models.ImageField(upload_to="images/")),
                ("file", models.FileField(upload_to="files/")),
                ("url", models.URLField()),
                ("email", models.EmailField(max_length=254)),
                ("slug", models.SlugField()),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("ip_address", models.GenericIPAddressField()),
                ("big_integer", models.BigIntegerField()),
                ("positive_integer", models.PositiveIntegerField()),
                ("small_integer", models.SmallIntegerField()),
                ("duration", models.DurationField()),
                ("json_data", models.JSONField()),
            ],
        ),
    ]
