# Generated by Django 5.1 on 2024-08-28 06:37

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todo",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelManagers(
            name="todo",
            managers=[
                ("default", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="todo",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
