# Generated by Django 5.0.7 on 2024-10-08 06:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0002_alter_todo_options_alter_todo_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
