class AuthResponseConstants:
    # fmt: off
    REGISTRATION_SUCCESS = "Registration Done. Please Activate Your Account!"
    EMAIL_ALREADY_EXISTS = "Email already exists"
    LOGIN_SUCCESS = "Login done successfully!"
    USER_FOUND = "User found successfully"
    RESET_TOKEN_RESENT = "Reset token mail sent successfully"
    INVALID_CREDENTIALS = "The email or password you entered is incorrect."
    NEW_TOKEN_GENERATED = "New token generated successfully"
    INCORRECT_OLD_PASSWORD = "Old password is not correct"
    PASSWORD_CONFIRMATION_MISMATCH = "Passwords do not match"
    PASSWORD_CHANGED = "Your password has been successfully updated."
    PASSWORD_RESET = "Your password has been reset successfully."
    EMAIL_VERIFIED = "Your email address has been verified successfully."
    EMAIL_VERIFICATION_LINK_EXPIRED = "Email verification link is invalid or has expired. Please request a new verification link"
    LOGOUT_SUCCESS = "You have successfully logged out."
    EMAIL_REVERIFICATION_SENT = "A new verification email has been sent. Please check your inbox."
    ACCOUNT_NOT_VERIFIED = "Your account is unverified. A new verification email has been sent."
    ACCOUNT_INACTIVE = "Your account is inactive. Please contact support for assistance."
    ACCOUNT_DELETED = "This account has been deleted and cannot be accessed."
    FORGOT_PASSWORD_EMAIL_SENT = "If this email is associated with an account, a password reset link has been sent."
    LOGIN_UNVERIFIED_EMAIL = "Your email is not verified. A new verification email has been dispatched. Please verify your email to log in."
    FORGOT_PASSWORD_UNVERIFIED_EMAIL = "Your email is not verified. A new verification email has been dispatched. Please verify your email to reset your password."
    TOKEN_GENERATION_FAILED="Token generation failed. Please try again later."
    INVALID_COGNITO_TOKEN = "Invalid Cognito token"
    MISSING_COGNITO_TOKENS = "Missing tokens from Cognito response"
    MISSING_COGNITO_FIELDS = "Cognito token missing required fields"
    COGNITO_TOKEN_EXCHANGE_FAILED = "Token exchange failed"
    TWO_FA_REQUIRED = "Two-factor authentication required"
    TWO_FA_SETUP_SUCCESS = "Scan QR to configure Google Authenticator"
    TWO_FA_VERIFICATION_FAILED = "Invalid TOTP code"

    # fmt: on
