# Generated by Django 4.1.3 on 2023-02-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otp",
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="otp_expires",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
