# Generated by Django 4.1.3 on 2023-02-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_otp_user_otp_expires"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.IntegerField(default=2),
        ),
    ]
