# Generated by Django 4.1.3 on 2023-06-08 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0039_alter_target_compose_result"),
        ("user", "0005_user_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="scanner.subscription",
            ),
        ),
    ]
