# Generated by Django 4.1.3 on 2023-06-08 08:26

from django.db import migrations


class Migration(migrations.Migration):

    def bulk_user_update(apps, schema_editor):
        Model = apps.get_model('user', 'User')
        records = list(Model.objects.all())
        for record in records:
            if record.is_staff or record.is_superuser:
                record.subscription_id = 2
            else:
                record.subscription_id = 1
        Model.objects.bulk_update(records, ['subscription_id'])

    dependencies = [
        ("user", "0006_alter_user_subscription"),
    ]

    operations = [
        migrations.RunPython(bulk_user_update)
    ]
