# Generated by Django 4.1.3 on 2023-07-27 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
    ]
