# Generated by Django 4.1.3 on 2023-07-27 06:57

from django.db import migrations
from user.models import User, Role

class Migration(migrations.Migration):

    def bulk_user_update(apps, schema_editor):
        Model = User
        records = list(Model.objects.all())
        for record in records:
            if record.is_superuser and record.is_staff:
                record.role = Role(id=1)
            elif not record.is_superuser and record.is_staff:
                record.role = Role(id=2)
            else:
                record.role = Role(id=3)
        Model.objects.bulk_update(records, ['role'])

    dependencies = [
        ("user", "0010_user_role"),
    ]

    operations = [
        migrations.RunPython(bulk_user_update)
    ]
