# Generated by Django 4.1.3 on 2023-07-28 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_map_role_with_all_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="role",
            old_name="tool_in_report",
            new_name="target_access",
        ),
        migrations.AddField(
            model_name="role",
            name="tool_access",
            field=models.BooleanField(default=False),
        ),
    ]
