# Generated by Django 4.1.3 on 2023-09-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_rename_tool_in_report_role_target_access_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="token_expiration",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
