# Generated by Django 4.1.3 on 2023-09-19 13:48

from django.db import migrations
from user.models import User

class Migration(migrations.Migration):

    def bulk_user_update(apps, schema_editor):
        Model = User
        records = list(Model.objects.all())
        for record in records:
            record.is_verified=True
        Model.objects.bulk_update(records, ['is_verified'])

    dependencies = [
        ("user", "0013_user_is_verified_user_token_expiration_and_more"),
    ]

    operations = [
        migrations.RunPython(bulk_user_update)
    ]