# Generated by Django 4.1.3 on 2023-09-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0014_map_is_verified_with_every_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="country_code",
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="mobile",
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
