# Generated by Django 4.1.3 on 2023-09-26 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0015_user_country_code_user_mobile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="mobile",
            new_name="mobile_number",
        ),
    ]
