# Generated by Django 4.1.3 on 2023-09-27 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0016_rename_mobile_user_mobile_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="client_name_access",
            field=models.BooleanField(default=True),
        ),
    ]
