# Generated by Django 4.1.3 on 2023-10-04 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0018_role_scan_result_access"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="role",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ("-created_at",)},
        ),
    ]
