# Generated by Django 4.1.3 on 2023-10-06 05:08

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0019_alter_role_options_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=user.models.User.upload_profile_to
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="user_company",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
