# Generated by Django 4.1.3 on 2023-10-10 10:37

from django.db import migrations
from user.models import User

class Migration(migrations.Migration):
    def bulk_user_update(apps, schema_editor):
        Model = User
        records = list(Model.objects.all())
        for record in records:
            record.save()

    dependencies = [
        ("user", "0020_user_profile_image_user_user_address_and_more"),
    ]

    operations = [
        migrations.RunPython(bulk_user_update)
    ]