# Generated by Django 4.1.3 on 2023-10-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0021_generate_letter_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="cover_content_access",
            field=models.BooleanField(default=False),
        ),
    ]
