# Generated by Django 4.1.3 on 2023-10-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0022_role_cover_content_access"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="stripe_customer_id",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
