# Generated by Django 4.1.3 on 2023-11-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0023_user_stripe_customer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="report_language",
            field=models.CharField(
                choices=[("EN", "EN"), ("FR", "FR")], default="EN", max_length=10
            ),
        ),
    ]
