# Generated by Django 4.1.3 on 2023-11-24 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0024_user_report_language"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="report_language",
            new_name="language",
        ),
    ]
