# Generated by Django 4.1.3 on 2022-12-02 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
                ('client', models.CharField(max_length=15)),
                ('result', models.TextField()),
                ('scanned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 12, 2, 7, 3, 36, 207935))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2022, 12, 2, 7, 3, 36, 207954))),
            ],
        ),
    ]
