# Generated by Django 4.1.3 on 2022-12-01 04:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
                ('result', models.TextField()),
                ('scanned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 12, 1, 4, 44, 53, 926648))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2022, 12, 1, 4, 44, 53, 926659))),
            ],
        ),
    ]
