# Generated by Django 4.1.3 on 2023-12-12 07:25

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import scanner.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("target_ip", models.CharField(max_length=100)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Created"),
                            (1, "In Progress"),
                            (2, "Failed"),
                            (3, "Finished"),
                        ],
                        default=0,
                    ),
                ),
                ("retry", models.BigIntegerField(default=0)),
                ("pdf_path", models.FileField(blank=True, null=True, upload_to="")),
                (
                    "scan_time",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "company_logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=scanner.models.Order.upload_logo_to,
                    ),
                ),
                ("company_name", models.CharField(blank=True, max_length=1000)),
                ("company_address", models.TextField(blank=True)),
                ("is_client", models.BooleanField(default=False)),
                ("client_name", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
            managers=[
                ("default", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("day_limit", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=11)),
                ("plan_type", models.CharField(max_length=255)),
                ("mail_scan_result", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
            managers=[
                ("default", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="SubscriptionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tools_ids", models.TextField(default="1")),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=11)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Fail"), (1, "Success")], default=0
                    ),
                ),
                ("transaction_payload", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Target",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("ip", models.CharField(max_length=100)),
                ("raw_result", models.BinaryField()),
                ("compose_result", models.JSONField(default=dict)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Created"),
                            (1, "Queued"),
                            (2, "Scan in-progress"),
                            (3, "Scan terminated"),
                            (4, "Scan finished"),
                        ],
                        default=0,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("pdf_path", models.FileField(blank=True, null=True, upload_to="")),
                ("retry", models.BigIntegerField(default=0)),
                (
                    "scan_time",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="targets",
                        to="scanner.order",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
            managers=[
                ("default", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("tool_name", models.CharField(max_length=50)),
                ("tool_cmd", models.CharField(max_length=500)),
                ("time_limit", models.BigIntegerField(default=30)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("sudo_access", models.BooleanField(default=False)),
                ("py_tool", models.BooleanField(default=False)),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="scanner.subscription",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
            managers=[
                ("default", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="TargetLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.IntegerField(
                        choices=[
                            (1, "TARGET_CREATED"),
                            (2, "TARGET_IN_QUEUE"),
                            (3, "TARGET_TERMINATED"),
                            (4, "TARGET_SCANNED"),
                            (5, "TARGET_DELETED"),
                            (6, "GENERATE_PDF"),
                            (7, "GENERATE_HTML"),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "target",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="scanner.target",
                    ),
                ),
            ],
        ),
    ]
