# Generated by Django 4.1.3 on 2022-12-14 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='tool',
            field=models.CharField(choices=[('nmap', 'nmap')], default='nmap', max_length=50),
        ),
        migrations.AlterField(
            model_name='machine',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 5, 34, 17, 73637)),
        ),
        migrations.AlterField(
            model_name='machine',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 5, 34, 17, 73653)),
        ),
    ]
