# Generated by Django 4.1.3 on 2022-12-15 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_machine_tool_alter_machine_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='tool',
        ),
        migrations.AlterField(
            model_name='machine',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 15, 4, 42, 13, 166394)),
        ),
        migrations.AlterField(
            model_name='machine',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 15, 4, 42, 13, 166411)),
        ),
    ]
