# Generated by Django 4.1.3 on 2022-12-15 05:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_remove_machine_tool_alter_machine_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=50)),
                ('tool_cmd', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 12, 15, 5, 49, 38, 88040))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2022, 12, 15, 5, 49, 38, 88055))),
            ],
        ),
        migrations.AlterField(
            model_name='machine',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 15, 5, 49, 38, 87511)),
        ),
        migrations.AlterField(
            model_name='machine',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 15, 5, 49, 38, 87528)),
        ),
        migrations.AddField(
            model_name='machine',
            name='tool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scanner.tool'),
        ),
    ]
