# Generated by Django 4.1.3 on 2022-12-20 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_tool_alter_machine_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='bg_task_status',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='scanned',
        ),
        migrations.AlterField(
            model_name='machine',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 20, 5, 29, 2, 712966)),
        ),
        migrations.AlterField(
            model_name='machine',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 20, 5, 29, 2, 712984)),
        ),
        migrations.AlterField(
            model_name='tool',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 20, 5, 29, 2, 713514)),
        ),
        migrations.AlterField(
            model_name='tool',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 20, 5, 29, 2, 713528)),
        ),
    ]
