# Generated by Django 4.1.3 on 2022-12-06 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_alter_machine_created_at_alter_machine_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 9, 26, 40, 702955)),
        ),
        migrations.AlterField(
            model_name='machine',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 9, 26, 40, 702968)),
        ),
    ]
