# Generated by Django 4.1.3 on 2022-12-20 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_remove_machine_bg_task_status_remove_machine_scanned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='status',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'Queued'), (2, 'Scan started'), (3, 'Scan terminated '), (4, 'Scan finished')], default=0),
        ),
        migrations.AlterField(
            model_name='machine',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 20, 5, 40, 13, 547262)),
        ),
        migrations.AlterField(
            model_name='machine',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 20, 5, 40, 13, 547279)),
        ),
        migrations.AlterField(
            model_name='tool',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 20, 5, 40, 13, 547799)),
        ),
        migrations.AlterField(
            model_name='tool',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 20, 5, 40, 13, 547815)),
        ),
    ]
