# Generated by Django 4.1.3 on 2022-12-06 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_alter_machine_created_at_alter_machine_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 9, 27, 42, 172693)),
        ),
        migrations.AlterField(
            model_name='machine',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 9, 27, 42, 172704)),
        ),
    ]
