# Generated by Django 4.1.3 on 2023-01-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0006_machine_status_alter_machine_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="machine",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Created"),
                    (1, "Queued"),
                    (2, "Scan started"),
                    (3, "Scan terminated"),
                    (4, "Scan finished"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="tool",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="tool",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
