# Generated by Django 4.1.3 on 2023-01-10 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0008_machine_scan_by_alter_machine_tool"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="machine",
            name="client",
        ),
    ]
