# Generated by Django 4.1.3 on 2023-01-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0009_remove_machine_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="pdf_path",
            field=models.FilePathField(blank=True, default="", null=True),
        ),
    ]
