# Generated by Django 4.1.3 on 2023-01-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0010_machine_pdf_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="pdf_path",
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
