# Generated by Django 4.1.3 on 2023-02-08 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0013_alter_machine_scan_by"),
    ]

    operations = [
        migrations.RenameModel('Machine', 'Target')
    ]
