# Generated by Django 4.1.3 on 2023-02-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0015_subscription_subscriptionhistory_tool_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionhistory",
            name="transaction_payload",
            field=models.JSONField(default=dict),
        ),
    ]
