# Generated by Django 4.1.3 on 2023-02-13 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("scanner", "0016_alter_subscriptionhistory_transaction_payload"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="subscription",
            managers=[
                ("default", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="target",
            managers=[
                ("default", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="tool",
            managers=[
                ("default", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="target",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="target",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tool",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="tool",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="target",
            name="scan_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="target",
            name="tool",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="scanner.tool",
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="scanner.subscription",
            ),
        ),
        migrations.CreateModel(
            name="TargetLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.IntegerField(
                        choices=[
                            (1, "TARGET_CREATED"),
                            (2, "TARGET_IN_QUEUE"),
                            (3, "TARGET_TERMINATED"),
                            (4, "TARGET_SCANNED"),
                            (5, "TARGET_DELETED"),
                            (6, "GENERATE_PDF"),
                            (7, "GENERATE_HTML"),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "target",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="scanner.target",
                    ),
                ),
            ],
        ),
    ]
