# Generated by Django 4.1.3 on 2023-02-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0017_alter_subscription_managers_alter_target_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="time_limit",
            field=models.BigIntegerField(default=30),
        ),
    ]
