# Generated by Django 4.1.3 on 2023-03-15 05:56

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0019_order_target_order"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="order",
            managers=[
                ("default", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
