# Generated by Django 4.1.3 on 2023-03-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0020_alter_order_managers_order_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="retry",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Created"), (1, "Queued"), (2, "Failed"), (3, "Finished")],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="target",
            name="retry",
            field=models.BigIntegerField(default=0),
        ),
    ]
