# Generated by Django 4.1.3 on 2023-03-15 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0021_order_retry_order_status_target_retry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="target",
            name="order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="targets",
                to="scanner.order",
            ),
        ),
    ]
