# Generated by Django 4.1.3 on 2023-03-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0022_alter_target_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
