# Generated by Django 4.1.3 on 2023-03-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0023_order_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="pdf_path",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
