# Generated by Django 4.1.3 on 2023-03-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0026_target_compose_result"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="target_ip",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="target",
            name="ip",
            field=models.CharField(max_length=100),
        ),
    ]
