# Generated by Django 4.1.3 on 2023-03-28 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0027_alter_order_target_ip_alter_target_ip"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="target",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="tool",
            name="is_active",
        ),
    ]
