# Generated by Django 4.1.3 on 2023-03-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0028_remove_subscription_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Created"),
                    (1, "In Progress"),
                    (2, "Failed"),
                    (3, "Finished"),
                ],
                default=0,
            ),
        ),
    ]
