# Generated by Django 4.1.3 on 2023-04-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0030_target_scan_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="target",
            name="scan_time",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
