# Generated by Django 4.1.3 on 2023-05-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0031_alter_target_scan_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="need_sudo_access",
            field=models.BooleanField(default=False),
        ),
    ]
