# Generated by Django 4.1.3 on 2023-05-01 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0032_tool_need_sudo_access"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tool",
            old_name="need_sudo_access",
            new_name="sudo_access",
        ),
    ]
