# Generated by Django 4.1.3 on 2023-05-19 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0033_rename_need_sudo_access_tool_sudo_access"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="subscription",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="target",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="tool",
            options={"ordering": ("-created_at",)},
        ),
    ]
