# Generated by Django 4.1.3 on 2023-05-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0034_alter_order_options_alter_subscription_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="py_tool",
            field=models.BooleanField(default=False),
        ),
    ]
