# Generated by Django 4.1.3 on 2023-06-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0035_tool_py_tool"),
    ]

    operations = [
        migrations.AddField(
            model_name="target",
            name="compose_result1",
            field=models.JSONField(default={}),
        ),
    ]
