# Generated by Django 4.1.3 on 2023-06-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0040_make_all_compose_result_empty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="target",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Created"),
                    (1, "Queued"),
                    (2, "Scan in-progress"),
                    (3, "Scan terminated"),
                    (4, "Scan finished"),
                ],
                default=0,
            ),
        ),
    ]
