# Generated by Django 4.1.3 on 2023-07-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0041_alter_target_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="scan_time",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
