# Generated by Django 4.1.3 on 2023-07-31 08:40

from django.db import migrations
from django.db.models import Sum
from scanner.models import Target, Order

class Migration(migrations.Migration):

    def bulk_target_update(apps, schema_editor):
        Model = Order
        records = list(Model.objects.all())
        for record in records:
            record.scan_time = Target.objects.filter(order_id=415).aggregate(Sum('scan_time'))['scan_time__sum']
        Model.objects.bulk_update(records, ['scan_time'])

    dependencies = [
        ("scanner", "0042_order_scan_time"),
    ]

    operations = [
        migrations.RunPython(bulk_target_update)
    ]
