# Generated by Django 4.1.3 on 2023-11-08 04:43

from django.db import migrations, models
import scanner.models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0044_subscription_mail_scan_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="company_logo",
            field=models.ImageField(
                blank=True, null=True, upload_to=scanner.models.Order.upload_logo_to
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="user_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="order",
            name="user_company",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
