# Generated by Django 4.1.3 on 2023-11-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0045_order_company_logo_order_user_address_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="user_address",
            new_name="company_address",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="user_company",
            new_name="company_name",
        ),
        migrations.AddField(
            model_name="order",
            name="is_client",
            field=models.BooleanField(default=False),
        ),
    ]
