# Generated by Django 4.1.3 on 2023-11-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0046_rename_user_address_order_company_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="client_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
