# Generated by Django 5.2.1 on 2025-06-09 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cognito_sub",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="token",
            name="jti",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="token",
            name="token_type",
            field=models.CharField(
                choices=[
                    ("access", "Access"),
                    ("refresh", "Refresh"),
                    ("reset", "Reset"),
                    ("verify_mail", "Verify Mail"),
                    ("google", "Google"),
                    ("otp", "Otp"),
                    ("id_token", "Id Token"),
                ],
                default="access",
                max_length=15,
            ),
        ),
        migrations.CreateModel(
            name="GroupProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "redirect_url",
                    models.URLField(
                        default="/", help_text="URL to redirect users of this group"
                    ),
                ),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="auth.group",
                    ),
                ),
            ],
        ),
    ]
