# Generated by Django 5.2.1 on 2026-01-18 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_is_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='totp_secret',
        ),
    ]
