# Generated by Django 5.2.1 on 2026-01-25 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_user_totp_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cognito_sub',
        ),
    ]
