"""
Django settings for proj project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from utils.config import load_settings

settings = load_settings()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = settings.SECRET_KEY


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = settings.DEBUG
UNIT_TEST_USER_EMAIL = settings.UNIT_TEST_USER_EMAIL
UNIT_TEST_USER_PASSWORD = settings.UNIT_TEST_USER_PASSWORD

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # installed
    "drf_spectacular",
    "rest_framework",
    "django_filters",
    "auth_api",
    "corsheaders",
    # django apps
    "users",
    "todos",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "proj.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "templates"),
            os.path.join(BASE_DIR, "proj/templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "proj.wsgi.application"
ASGI_APPLICATION = "proj.asgi.application"


# Database

DATABASES = {
    "default": {
        "ENGINE": settings.SQL_ENGINE,
        "NAME": settings.SQL_DATABASE,
        "USER": settings.SQL_USER,
        "PASSWORD": settings.SQL_PASSWORD,
        "HOST": settings.SQL_DATABASE_HOST,
        "PORT": settings.SQL_DATABASE_PORT,
        "CONN_MAX_AGE": 60,
        # 'OPTIONS': {
        #     # "init_command": f"SET GLOBAL max_connections = 100000",
        #     'MAX_AGE': 600
        # }
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


SPECTACULAR_SETTINGS = {
    "TITLE": "DRF Boilerplate",
    "DESCRIPTION": "DRF- Boilerplate",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,  # Exclude schema from the public Swagger UI
    "SCHEMA_PATH_PREFIX": "/api/",  # Adjust according to your path structure
    "SECURITY": [
        {
            "basicAuth": []  # Enable Basic Auth in the API documentation
        },
    ],
    "COMPONENTS": {
        "securitySchemes": {
            "basicAuth": {
                "type": "http",
                "scheme": "basic",
            }
        }
    },
    "SERVERS": [{"url": i} for i in settings.CSRF_TRUSTED_ORIGINS.split()],
}


# CORS & CSRF allowed origins
CSRF_TRUSTED_ORIGINS = settings.CSRF_TRUSTED_ORIGINS.split()
CORS_ORIGIN_WHITELIST = settings.CORS_ORIGIN_WHITELIST.split()

# CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_ALL_ORIGINS = True

# By pass http to https
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Django Rest Framework and JWT and CORS
AUTH_THROTTLING_LIMIT = os.environ.get(
    "AUTH_THROTTLING_LIMIT", os.getenv("AUTH_THROTTLING_LIMIT", "20/hour")
)
REST_FRAMEWORK = {
    "EXCEPTION_HANDLER": "utils.exception_handler.custom_exception_handler",
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "utils.authentication.CustomJWTAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_THROTTLE_RATES": {
        "auth": AUTH_THROTTLING_LIMIT,
    },
    "DEFAULT_PAGINATION_CLASS": "utils.pagination.BasePagination",
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

# SIMPLE_JWT
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=settings.AUTH_ACCESS_TOKEN_LIFELINE),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=settings.AUTH_REFRESH_TOKEN_LIFELINE),
    "ALGORITHM": settings.JWT_ALGORITHM,
    "SIGNING_KEY": settings.SECRET_KEY,
}

AUTH_USER_MODEL = "auth_api.User"

# Base url to serve media files
MEDIA_URL = "/media/"

# Path where media is stored
MEDIA_ROOT = os.path.join(BASE_DIR, "media/")


# EMAIL
EMAIL_HOST = settings.EMAIL_HOST
EMAIL_PORT = settings.EMAIL_PORT
EMAIL_USE_TLS = settings.EMAIL_USE_TLS
EMAIL_USE_SSL = settings.EMAIL_USE_SSL
EMAIL_BACKEND = settings.EMAIL_BACKEND
EMAIL_HOST_USER = settings.EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = settings.EMAIL_HOST_PASSWORD
EMAIL_FORM_NAME = settings.EMAIL_FORM_NAME


FRONTEND_URL = settings.FRONTEND_URL


# GOOGLE SSO
GOOGLE_CLIENT_ID = settings.GOOGLE_CLIENT_ID
GOOGLE_CLIENT_SECRET = settings.GOOGLE_CLIENT_SECRET

# PASSWORD validation
PASSWORD_VALIDATE_STRING = "A minimum 8 characters and maximum 30 character password contains a combination of uppercase and lowercase letter, special symbol and number are required."
PASSWORD_VALIDATE_REGEX = r"^(?=\S*[a-z])(?=\S*[A-Z])(?=\S*\d)(?=\S*[^\w\s])\S{8,30}$"

# Create Logs folder
if not os.path.exists(f"{BASE_DIR}/logs/"):
    os.mkdir(f"{BASE_DIR}/logs/")

# Create log file is not exist
if not os.path.exists(f"{BASE_DIR}/logs/info.log"):
    f = open(f"{BASE_DIR}/logs/info.log", "w")
    f.close()

if not os.path.exists(f"{BASE_DIR}/logs/error.log"):
    f = open(f"{BASE_DIR}/logs/error.log", "w")
    f.close()

# Logging
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False if DEBUG else True,
    "handlers": {
        "info": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": f"{BASE_DIR}/logs/info.log",
            "maxBytes": 30 * 1024 * 1024,  # 30M Log Size
            "backupCount": 10,
            "formatter": "info",
        },
        "error": {
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": f"{BASE_DIR}/logs/error.log",
            "maxBytes": 30 * 1024 * 1024,  # 30M Log Size
            "backupCount": 5,
            "formatter": "error",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["info", "error"],
            "level": "INFO",
            "propagate": True,
        },
    },
    "formatters": {
        "info": {
            "format": "%(levelname)s %(asctime)s %(module)s %(lineno)s %(message)s",
        },
        "error": {
            "format": "%(asctime)s [%(module)s | %(levelname)s] %(message)s @ %(pathname)s : %(lineno)d : %(funcName)s",
        },
    },
}

AUTHENTICATION_BACKENDS = [
    "auth_api.custom_backend.LoginOnAuthBackend",  # Custom backend
]

# Swagger Authentication
SWAGGER_AUTH_USERNAME = settings.SWAGGER_AUTH_USERNAME
SWAGGER_AUTH_PASSWORD = settings.SWAGGER_AUTH_PASSWORD

# Token Lifespan
AUTH_VERIFY_EMAIL_TOKEN_LIFELINE = settings.AUTH_VERIFY_EMAIL_TOKEN_LIFELINE
AUTH_RESET_PASSWORD_TOKEN_LIFELINE = settings.AUTH_RESET_PASSWORD_TOKEN_LIFELINE
OTP_EXPIRY_MINUTES = settings.OTP_EXPIRY_MINUTES

# Configs
PROJECT_TITLE = settings.PROJECT_TITLE
SUPERUSER_EMAIL = settings.SUPERUSER_EMAIL
